version: '3.8'
services:
  ivandjoh-db:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookmark_db
    networks:
      - ivandjoh-online
